---
title: "COVID 19's Affect on 2020 NFL sports betting"
author: "INFO 201 Lab AC Group 3"
date: "2/13/2020"
output: html_document
---
Main Question: How did the pandemic affect the betting markets of the 2020 NFL season.

```{r setup, include = FALSE}
source("scripts:/summaryinfo.R")

library("knitr")
```

## Project Intro
This project aims to answer the question: _How did the COVID 19 pandemic affect the betting markets during the 2020 NFL season._ Sports betting is common worldwide, and this project focuses specifically on wagers placed on players and games from the United State's National Football League (NFL). There is a wide range in the level of participation for sports betting: from casual fans to serious money-making fanatics. Regardless of motivations, all sports bets follow three simple steps: selection, stakes, and odds. The most popular types of sports bets are on point spreads and totals, where people often use statistics to decide on their bet and then wait for the game to be played to see the outcome. Betting is always a gamble, and sports betting involves necessary risk. Sports betting often happens online, which is where this project is focusing. We choose this domain because of a shared interest in sports, and curiosity about the world of football betting. This project will examine trends in NFL betting, especially how the COVID 19 pandemic has affected football betting and team play.
(more...?)

## Summary Information 
Our dataset includes `r summary_info$num_obs` observations that contain values in the favorite team and spread favorite columns. We specifically chose to keep the observations with these variables since we want to study the trend of the betting. This turned out to be around `r summary_info$num_unique_years` seasons worth of data with `r summary_info$num_different_teams` different teams. Since we have more teams than the normal amount, we will have to take into account for teams that were created or folded. But ignoring the rows without spread data, the smallest spread turned out to be `r summary_info$favorite_min_spread`, which is also considered a 50/50 game or a tossup. Our biggest spread turned out be `r summary_info$favorite_max_spread`, which is considered to be a very one sided game. However, our mean turned out to be `r summary_info$favorite_spread_mean`, which was much closer to a 50/50 game than a one sided game. 

aggregate table + label

3 charts + label